# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.IntegerField()),
                ('pub_date', models.DateTimeField(verbose_name='Date published')),
                ('document_for_update', models.CharField(max_length=8)),
                ('comments_for_revision', models.CharField(max_length=400)),
                ('writer', models.CharField(max_length=50)),
                ('writer_email', models.CharField(max_length=50)),
                ('editor', models.CharField(max_length=50)),
                ('editor_email', models.CharField(max_length=50)),
                ('close_date', models.DateTimeField(verbose_name='Date closed')),
                ('major_revision', models.CharField(max_length=2)),
                ('minor_revision', models.CharField(max_length=2)),
            ],
        ),
    ]
