# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-25 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField(max_length=100)),
                ('document_number', models.CharField(max_length=30)),
                ('comments_for_revision', models.CharField(max_length=500)),
                ('reported_by', models.CharField(max_length=50)),
                ('reported_by_email', models.CharField(max_length=50)),
                ('editor', models.CharField(max_length=50)),
                ('editor_email', models.CharField(max_length=50)),
                ('major_revision', models.CharField(max_length=2)),
                ('minor_revision', models.CharField(max_length=2)),
                ('confirmed', models.BooleanField(default=False)),
                ('close_date', models.CharField(max_length=100)),
            ],
        ),
    ]
