# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-01 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField(default=django.utils.timezone.now, max_length=100)),
                ('document_number', models.CharField(max_length=30)),
                ('comments_for_revision', models.CharField(max_length=500)),
                ('reported_by', models.CharField(max_length=50)),
                ('reported_by_email', models.EmailField(max_length=50)),
                ('url_of_issue', models.CharField(blank=True, max_length=200)),
                ('pic_of_issue', models.FileField(blank=True, upload_to='')),
                ('eng', models.CharField(blank=True, max_length=50)),
                ('eng_email', models.EmailField(blank=True, max_length=50)),
                ('revision', models.CharField(blank=True, max_length=4)),
                ('eng_comments', models.CharField(blank=True, max_length=1000)),
                ('confirmed', models.BooleanField(default=False)),
                ('close_date', models.DateField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
