# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-25 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='close_date',
            field=models.DateField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='editor_email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='reported_by_email',
            field=models.EmailField(max_length=50),
        ),
    ]
