# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 23:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='document_for_update',
            new_name='document_number',
        ),
    ]
