# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-01 00:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20160825_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='editor_email',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='major_revision',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='minor_revision',
        ),
        migrations.AddField(
            model_name='ticket',
            name='eng',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ticket',
            name='eng_comments',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='ticket',
            name='eng_email',
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ticket',
            name='revision',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='close_date',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now, max_length=100),
        ),
    ]
