# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-16 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_remove_ticket_ticket_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='editor_email',
            field=models.EmailField(max_length=50),
        ),
    ]
