# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-16 17:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20160816_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='pub_date',
        ),
    ]
