# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-16 17:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_remove_ticket_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='close_date',
        ),
    ]
