# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-17 02:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_remove_ticket_close_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 17, 2, 42, 51, 616807, tzinfo=utc)),
        ),
    ]
