# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_auto_20160818_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='pub_date',
            field=models.CharField(max_length=20),
        ),
    ]
