# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-20 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_auto_20160820_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='editor_email',
            field=models.CharField(max_length=50),
        ),
    ]
