# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 00:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_auto_20160820_0220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='writer',
            new_name='reported_by',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='writer_email',
            new_name='reported_by_email',
        ),
        migrations.AddField(
            model_name='ticket',
            name='close_date',
            field=models.DateTimeField(default=None, verbose_name='Date closed'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='pub_date',
            field=models.CharField(default=datetime.datetime(2016, 8, 24, 0, 1, 40, 428242, tzinfo=utc), max_length=20),
        ),
    ]
