# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 00:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_auto_20160824_0001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='close_date',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='pub_date',
            field=models.CharField(default=datetime.datetime(2016, 8, 24, 0, 6, 9, 970540, tzinfo=utc), max_length=20),
        ),
    ]
