# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_auto_20160824_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='pub_date',
            field=models.CharField(max_length=20),
        ),
    ]
