# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-01 21:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='pic_of_issue',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='url_of_issue',
        ),
    ]
