# Generated by Django 2.0a1 on 2017-10-29 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_auto_20171029_0612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='reported_by_email',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='reported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
