# Generated by Django 2.0a1 on 2017-10-29 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_auto_20171029_0650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='eng_email',
        ),
        migrations.AlterField(
            model_name='note',
            name='eng',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
